Fix incorrect broadcast address
linux-can/socketcand pull request #26
Opened 2023-01-27 05:13 UTC by faisal-shah

On at least some linux systems, the broadcast address is unset (0.0.0.0). Firstly, this is incorrect. Secondly it is not allowed per RFC1122 3.2.1.3 (a):
https://www.rfc-editor.org/rfc/rfc1122#section-3

The broadcast address is computed from the ip address, and net mask. broadcast = ip | ~net_mask

This remains the correct vale of the broadcast address regardless of what SIOCGIFBRDADDR returns. As it will be garbage if no one ever set it (with SIOCSIFBRDADDR perhaps).

This issue was exposed when attempting to use the loopback network interface. I've tried a few different distros, and on all of them the broadcast mask was unset (0.0.0.0). However, on all of them the following route was set (127.255.255.255 being the broadcast address for 127.0.0.1/8) and resulted in broadcasts being tranmistted and received properly:

$ ip route get 127.255.255.255
broadcast 127.255.255.255 dev lo table local src 127.0.0.1 uid 1000
    cache <local,brd>

2023-01-27 10:55 UTC, marckleinebudde requested changes

2023-01-27 10:55 UTC, marckleinebudde commented on socketcand.c
> +    broadcast_addr.sin_addr.s_addr |= ~((struct sockaddr_in *) &ifr_mask.ifr_netmask)->sin_addr.s_addr;
Nitpick: please indent with <TAB> here, too

2023-01-27 13:25 UTC, faisal-shah commented on socketcand.c
> +    broadcast_addr.sin_addr.s_addr |= ~((struct sockaddr_in *) &ifr_mask.ifr_netmask)->sin_addr.s_addr;
Fixed. Amended the commit and force pushed. Thank you.

2023-01-27 13:30 UTC, marckleinebudde commented on socketcand.c
> +    broadcast_addr.sin_addr.s_addr |= ~((struct sockaddr_in *) &ifr_mask.ifr_netmask)->sin_addr.s_addr;
I think something went wrong.....please recheck.

2023-01-27 15:53 UTC, marckleinebudde commented on socketcand.c
> +    broadcast_addr.sin_addr.s_addr |= ~((struct sockaddr_in *) &ifr_mask.ifr_netmask)->sin_addr.s_addr;
looks good

2023-01-27 15:54 UTC, marckleinebudde commented
Although the style of the code is fixes, I cannot say anything to the contents of this PR. Maybe @hartkopp can help.

2023-01-27 18:30 UTC, faisal-shah commented on socketcand.c
> +    broadcast_addr.sin_addr.s_addr |= ~((struct sockaddr_in *) &ifr_mask.ifr_netmask)->sin_addr.s_addr;
Can you approve the review request? It still shows up at 1 change requested.

2023-01-27 20:49 UTC, hartkopp commented
> Although the style of the code is fixes, I cannot say anything to the contents of this PR. Maybe @hartkopp can help.

Not really! I only show up in that code section due to style fixes. I assume @dschanoeh knows better ...

2023-01-28 08:32 UTC, dschanoeh commented
I'm not sure if I'm the right one to judge since I haven't touched or used this in years but my interpretation is that there is something wrong in those distros - I couldn't find anything regarding a deprecation of `SIOCGIFBRDADDR` or known limitations. So the original code doesn't seem obviously wrong.
Nevertheless, calculating it manually seems like a good workaround and I don't see other problems arising from this.

2023-01-28 13:05 UTC, marckleinebudde approved these changes

2023-01-28 13:06 UTC, marckleinebudde commented
Ok - then let's merge this.

2023-01-28 13:06 UTC, merged

2023-01-28 13:39 UTC, faisal-shah commented
Thanks for being responsive!