Update docs to reflect actual implementation.
linux-can/socketcand pull request #27
Opened 2023-01-28 15:16 UTC by faisal-shah

Correct the documentation to describe the data bytes of < send > and < frame >

For < send >, it's supposed to be lowercase unpadded (%hhx) with spaces in-between data bytes:
https://github.com/linux-can/socketcand/blob/master/state_raw.c#L158-L171

And on the receive side (< frame > message), the data is padded uppercase (%02X) without spaces in between:
https://github.com/linux-can/socketcand/blob/master/state_raw.c#L125-L135

2023-01-28 15:19 UTC, marckleinebudde requested changes

2023-01-28 15:19 UTC, marckleinebudde commented on doc/protocol.md
> +Reception of a CAN frame with CAN ID 0x123 , data length 4 and data 0x1A, 0x22, 0x03 and 0x44 at time 23.424242>.
nitpick: please remove trailing whitespace

2023-01-30 03:30 UTC, faisal-shah commented on doc/protocol.md
> +Reception of a CAN frame with CAN ID 0x123 , data length 4 and data 0x1A, 0x22, 0x03 and 0x44 at time 23.424242>.
Fixed trailing whitespace

2023-01-30 08:28 UTC, marckleinebudde commented on doc/protocol.md
> +Reception of a CAN frame with CAN ID 0x123 , data length 4 and data 0x1A, 0x22, 0x03 and 0x44 at time 23.424242>.
Thanks for removing the other trailing whitespace!

2023-01-30 08:28 UTC, merged