Add support for CAN interfaces configurations based on libsocketcan
linux-can/socketcand pull request #35
Opened 2024-11-26 15:32 UTC by jjorge-geotab

#  Summary 

This is a PR proposal to implement the CAN interfaces configurations using libsocketcan. In order to do that, the following changes were performed:

- Refactor in the nobus state, as far as all the logic there is running out of control in the main file (socketcand.c) and to follow the same rationale used for the other states (the state function implemented in a sepparated file / function) 
- Adding of canctl.c file to implement the functions to perform the interfaces configuration.
- Adding the libsocketcan reference / dependency in the autotools.
- If the libsocketcan dependency check fails, the library will implement mock functions or errors (depending on the function) 

# Test

Tested with a custom gs_usb dongle based on STM32G0 and candlelight firmware. The tests were performed in ubuntu 22.04:

``` sudo ./socketcand -i can0```

Test the client using teltnet in other terminal: 

```telnet localhost 29536```

Then, we can perform a basic config of the interface:

```
< hi >< can0 B 500000 -1 -1 -1 -1 -1 -1 -1 >
< ok >< can0 C 1 1 0 >
< ok >< open can0 >
```

As soon as the <open>  command is executed, the interface starts to work and we have the following config available in the system:

```7: can0: <NOARP,UP,LOWER_UP,ECHO> mtu 16 qdisc pfifo_fast state UP mode DEFAULT group default qlen 10
    link/can  promiscuity 0 minmtu 0 maxmtu 0 
    can <LOOPBACK> state ERROR-ACTIVE restart-ms 0 
	  bitrate 500000 sample-point 0.875 
	  tq 25 prop-seg 34 phase-seg1 35 phase-seg2 10 sjw 5
	  gs_usb: tseg1 1..256 tseg2 1..128 sjw 1..128 brp 1..512 brp-inc 1
	  termination 0 [ 0, 120 ]
	  clock 40000000 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 parentbus usb parentdev 3-1.1.2:1.0 
```
Now if we filter and send, we can see the device working in loopback mode:

```
< filter 0 0 123 1 FF >
< send 123 0 >
< frame 123 1732634826.235033  >
```

2024-12-05 07:48 UTC, jjorge-geotab commented
Hi @marckleinebudde 

I noticed that there is no activity on this PR after several days. Probably I missed any step to move this request fordward. Is there any procedure description to follow the steps to evaluate this PR.

Obviously, I will rebase the change because now is conflicting.

2024-12-05 08:02 UTC, marckleinebudde commented
I'm not a user of `socketcand`, it just happened that I can merge PR here.

You probably want to update https://github.com/linux-can/socketcand/blob/master/doc/protocol.md, too.

Since https://github.com/linux-can/socketcand/pull/40 we have an editorconfig, please use tabs for indention.

Move the `if HAVE_LIBSOCKETCAN` out of the `.c` file into the header file.

2024-12-05 08:21 UTC, jjorge-geotab commented on canctl.h
> +int canctl_set_control_modes(char *bus_name, char *buff_control_modes_conf, int buff_length);
Ok,  first I will rebase the branch and then I will rebase the changes.

2024-12-05 12:35 UTC, jjorge-geotab commented on canctl.h
> +int canctl_set_control_modes(char *bus_name, char *buff_control_modes_conf, int buff_length);
I already rebased the branch and added the changes you suggested. The functionality was also tested again with the gs_usb device and it works properly.

2024-12-05 14:03 UTC, jjorge-geotab commented on canctl.c
> +	sscanf(buff_control_modes_conf, "< %*s C %d %d %d >",
Fixed

2024-12-05 14:03 UTC, jjorge-geotab commented on canctl.c
> +	sscanf(buff_bittiming_conf, "< %*s B %d %d %d %d %d %d %d %d >",
Fixed

2024-12-05 14:03 UTC, jjorge-geotab commented on canctl.c
> +	return (can_do_stop(bus_name) || can_set_bittiming(bus_name, &bt));
Fixed

2024-12-05 14:03 UTC, jjorge-geotab commented on canctl.c
> +	return (can_do_stop(bus_name) || can_set_ctrlmode(bus_name, &cm));
Fixed

2024-12-05 14:06 UTC, marckleinebudde commented on canctl.c
> +int canctl_set_bittiming(char *bus_name, char *buff_bittiming_conf, int buff_length) {
```suggestion
int canctl_set_bittiming(const char *bus_name, const char *buff_bittiming_conf, int buff_length) {
```

2024-12-05 14:11 UTC, jjorge-geotab commented on canctl.c
> +int canctl_set_bittiming(char *bus_name, char *buff_bittiming_conf, int buff_length) {
Fixed

2024-12-05 14:12 UTC, marckleinebudde requested changes

2024-12-05 14:12 UTC, marckleinebudde commented on canctl.c
> +	{
```suggestion
	if (items != 8)	{
```

2024-12-05 14:12 UTC, marckleinebudde commented on canctl.c
> +int canctl_start_iface(char *bus_name){
```suggestion
int canctl_start_iface(const char *bus_name){
```

2024-12-05 14:12 UTC, marckleinebudde commented on canctl.c
> +int canctl_set_control_modes(char *bus_name, char *buff_control_modes_conf, int buff_length) {
```suggestion
int canctl_set_control_modes(const char *bus_name, const char *buff_control_modes_conf, int buff_length) {
```

2024-12-05 14:12 UTC, marckleinebudde commented on canctl.c
> +	cm.flags = 0;
```suggestion
	struct can_ctrlmode cm = {
		.mask = CAN_CTRLMODE_LOOPBACK | CAN_CTRLMODE_LOOPBACK | CAN_CTRLMODE_3_SAMPLES,
	};
```

2024-12-05 14:12 UTC, marckleinebudde commented on canctl.c
> +	return !(can_do_stop(bus_name) || can_set_ctrlmode(bus_name, &cm)) ? 0 : -1;
```suggestion

	return !(can_do_stop(bus_name) || can_set_ctrlmode(bus_name, &cm)) ? 0 : -1;
```

2024-12-05 14:14 UTC, jjorge-geotab commented on canctl.c
> +int canctl_start_iface(char *bus_name){
done

2024-12-05 14:14 UTC, jjorge-geotab commented on canctl.c
> +int canctl_set_control_modes(char *bus_name, char *buff_control_modes_conf, int buff_length) {
done

2024-12-05 14:16 UTC, marckleinebudde requested changes

2024-12-05 14:16 UTC, marckleinebudde commented on canctl.c
> +int canctl_start_iface(const char *bus_name){
```suggestion
int canctl_start_iface(const char *bus_name) {
```

2024-12-05 14:16 UTC, marckleinebudde commented on canctl.c
> +int canctl_set_control_modes(const char *bus_name, const char *buff_control_modes_conf, int buff_length) {
```suggestion
int canctl_set_control_modes(const char *bus_name, const char *buff_control_modes_conf, int buff_length)
{
```

2024-12-05 14:16 UTC, marckleinebudde commented on socketcand.c
> +	for(i=0;i<interface_count;i++) {
```suggestion

int check_bus(const char *bus_name)
{
	int found = 0, i;
	
	for (i = 0; i < interface_count; i++) {
```

2024-12-05 14:16 UTC, marckleinebudde commented on socketcand.c
> +		if(!strcmp(interface_names[i], bus_name))
```suggestion
		if (!strcmp(interface_names[i], bus_name))
```

2024-12-05 14:17 UTC, marckleinebudde commented
Please use tabs in `state_nobus.c`.

2024-12-05 14:23 UTC, jjorge-geotab commented on canctl.c
> +int canctl_set_control_modes(const char *bus_name, const char *buff_control_modes_conf, int buff_length) {
Do you want me to move all the braces in my code files to a new line?

2024-12-05 14:27 UTC, jjorge-geotab commented on canctl.c
> +	{
done

2024-12-05 14:29 UTC, marckleinebudde commented on canctl.c
> +int canctl_set_control_modes(const char *bus_name, const char *buff_control_modes_conf, int buff_length) {
Only for functions. Following kernel coding style.

2024-12-05 14:29 UTC, jjorge-geotab commented on canctl.c
> +	return !(can_do_stop(bus_name) || can_set_ctrlmode(bus_name, &cm)) ? 0 : -1;
done

2024-12-05 14:30 UTC, jjorge-geotab commented on canctl.c
> +int canctl_start_iface(const char *bus_name){
done

2024-12-05 14:31 UTC, jjorge-geotab commented on canctl.c
> +int canctl_set_control_modes(const char *bus_name, const char *buff_control_modes_conf, int buff_length) {
ok, I will do that for the rest of the functions. I left it that way because I saw the rest of the functions with the same format.

2024-12-05 14:31 UTC, jjorge-geotab commented on socketcand.c
> +	for(i=0;i<interface_count;i++) {
done

2024-12-05 14:31 UTC, jjorge-geotab commented on socketcand.c
> +		if(!strcmp(interface_names[i], bus_name))
done

2024-12-05 14:33 UTC, jjorge-geotab commented on canctl.c
> +int canctl_set_control_modes(const char *bus_name, const char *buff_control_modes_conf, int buff_length) {
done for all the functions created by me

2024-12-05 14:34 UTC, marckleinebudde requested changes

2024-12-05 14:34 UTC, marckleinebudde commented on canctl.c
> +int canctl_set_bittiming(const char *bus_name, const char *buff_bittiming_conf, int buff_length) {
```suggestion
int canctl_set_bittiming(const char *bus_name, const char *buff_bittiming_conf, int buff_length)
{
```

2024-12-05 14:34 UTC, marckleinebudde commented on canctl.c
> +int canctl_start_iface(const char *bus_name) {
```suggestion
int canctl_start_iface(const char *bus_name)
{
```

2024-12-05 14:34 UTC, marckleinebudde commented on canctl.c
> +int canctl_start_iface(const char *bus_name) {
can we make the function `static`?

2024-12-05 14:34 UTC, marckleinebudde commented on state_nobus.c
> +	if(i != 0) {
```suggestion
	if (i != 0) {
```

2024-12-05 14:34 UTC, marckleinebudde commented on state_nobus.c
> +	if(!strncmp("< open ", buf, 7)) {
```suggestion
	if (!strncmp("< open ", buf, 7)) {
```

2024-12-05 14:34 UTC, marckleinebudde commented on state_nobus.c
> +		if(canctl_start_iface (bus_name)) {
```suggestion
		if (canctl_start_iface (bus_name)) {
```

2024-12-05 14:34 UTC, marckleinebudde commented on state_nobus.c
> +	}else {
```suggestion
	} else {
```

2024-12-05 14:34 UTC, marckleinebudde commented on state_nobus.c
> +					goto SHUTDOWN_ERR;
please use lower case jump labels

2024-12-05 14:34 UTC, marckleinebudde commented on state_nobus.c
> +				if(canctl_set_bittiming(bus_name, buf, strlen(buf))) {
```suggestion
				if (canctl_set_bittiming(bus_name, buf, strlen(buf))) {
```

2024-12-05 14:36 UTC, jjorge-geotab commented on canctl.c
> +int canctl_start_iface(const char *bus_name) {
yes, we can, the function only contains the libsocketcan call.

2024-12-05 14:41 UTC, jjorge-geotab commented on canctl.c
> +int canctl_start_iface(const char *bus_name) {
done

2024-12-05 14:42 UTC, jjorge-geotab commented on state_nobus.c
> +	if(i != 0) {
done

2024-12-05 14:43 UTC, jjorge-geotab commented on state_nobus.c
> +					goto SHUTDOWN_ERR;
done

2024-12-05 14:43 UTC, jjorge-geotab commented on state_nobus.c
> +	}else {
done

2024-12-05 14:44 UTC, jjorge-geotab commented on state_nobus.c
> +				if(canctl_set_bittiming(bus_name, buf, strlen(buf))) {
done

2024-12-05 14:52 UTC, marckleinebudde requested changes

2024-12-05 14:52 UTC, marckleinebudde commented on canctl.c
> +	);
```suggestion
		&listen_only, &loopback, &three_samples);
```

2024-12-05 14:52 UTC, marckleinebudde commented on include/linux/canctl.h
> + * canctl_start_iface - set up control modes for given interface.
copy/paste error :)

2024-12-05 14:52 UTC, marckleinebudde commented on include/linux/canctl.h
> +static int canctl_start_iface(const char *bus_name)
```suggestion
static inline int canctl_start_iface(const char *bus_name)
```

2024-12-05 14:52 UTC, marckleinebudde commented on state_nobus.c
> +	if(previous_state != STATE_NO_BUS) {
```suggestion
	if (previous_state != STATE_NO_BUS) {
```

2024-12-05 14:52 UTC, marckleinebudde commented on state_nobus.c
> +	i = receive_command(client_socket, (char *) &buf);
I think the cast is not needed

```suggestion
	i = receive_command(client_socket, &buf);
```

2024-12-05 14:52 UTC, marckleinebudde commented on include/linux/canctl.h
> +	return -EINVAL;
Does this break the non libsocketcan case? The `open` command will fail.

2024-12-05 14:53 UTC, jjorge-geotab commented on include/linux/canctl.h
> +	return -EINVAL;
You're right, I'll change it.

2024-12-05 15:00 UTC, jjorge-geotab commented on state_nobus.c
> +	i = receive_command(client_socket, (char *) &buf);
Whithout the cast you receive a warning `../socketcand.h:57:39: note: expected ‘char *’ but argument is of type ‘char (*)[8290]’`.

I also inherited this from the old nobus implementation, but I think this was the reason behind the cast.

2024-12-05 15:02 UTC, jjorge-geotab commented on include/linux/canctl.h
> +	return -EINVAL;
fixed

2024-12-05 15:03 UTC, jjorge-geotab commented on canctl.c
> +	);
fixed

2024-12-05 15:03 UTC, jjorge-geotab commented on include/linux/canctl.h
> + * canctl_start_iface - set up control modes for given interface.
fixed

2024-12-05 15:03 UTC, jjorge-geotab commented on include/linux/canctl.h
> +static int canctl_start_iface(const char *bus_name)
fixed for all the static functions in canctl.h

2024-12-05 15:04 UTC, jjorge-geotab commented on state_nobus.c
> +	if(previous_state != STATE_NO_BUS) {
done

2024-12-05 15:15 UTC, jjorge-geotab commented on state_nobus.c
> +	i = receive_command(client_socket, (char *) &buf);
You're right, fixed

2024-12-05 15:23 UTC, marckleinebudde commented
The rest looks good.

2024-12-05 15:28 UTC, jjorge-geotab commented on socketcand.c
> +int check_bus(const char *bus_name)
ok, I moved it

2024-12-05 15:29 UTC, jjorge-geotab commented
Next time, in order to avoid all the format issues I would like to know if you're using a style check script (like the kernel one or something simillar)

Thanks for the help!

2024-12-05 16:13 UTC, marckleinebudde approved these changes

2024-12-05 16:13 UTC, merged

2024-12-07 18:36 UTC, yegorich commented
@jjorge-geotab @marckleinebudde looks like `canctl.h` file should go to `src` as it doesn't belong to the kernel headers?